### ISSUE TITLE
Can't change the position of date picker 

### ISSUE THREAD

**Issue by sajjidakr** [720kb/angular-datepicker#106]
I am unable to change the position of the calender (with respect to input filed). Like if the width of the input field is minimum the position of the date picker is right to input filed but i want it to be left Any help would be great

**Comment by 45kb** [comment]
Hi, yes, the datepicker calendar inherits from the input width, you could try to edit the css, and if not enough to use some js to make it on the very left of the input:

```css
._720kb-datepicker-calendar{
/*margin-left: -0.5%;*/
margin-left:-100%;
/*width:101%;*/
width:200px;
}
```
