### ISSUE TITLE
Have calendar in always open state?

### ISSUE THREAD

**Issue by lolz0r** [720kb/angular-datepicker#146]
How can one have the calendar always be open without requiring first a click onto the input element?

**Comment by 45kb** [comment]
Hi @lolz0r  you can use this:

```css
._720kb-datepicker-calendar{
visibility:visible;
}
```
