### ISSUE TITLE
"Today" disappears once a day is selected

### ISSUE THREAD

**Issue by amirgon** [720kb/angular-datepicker#290]
I've added the following to my CSS:

```css
_720kb-datepicker-calendar-day._720kb-datepicker-today {
  background:red;
  color:white;
}
```

"Today" is marked in red. But once a day is selected, **marking disappears and never returns**, even when datepicker is closed and opened again.

Example: https://embed.plnkr.co/WJBn3O8DH4rVP7HWQ6KP/
(select a date, then select a date again. "Today" is no longer marked)
